server:
  port: 9001

spring:
  application:
    name: cloud-gateway

  cloud:
    gateway:
      #      跨域配置文件
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedHeaders: "*"
            allowedMethods: "*"
            allowCredentials: true
      discovery:
        locator:
          enabled: true #开启后,新增一种访问方式:localhost:9527/服务名/资源路径 原访问方式为localhost:9527/资源路径 #是否使用service-id 的小写， 默认是大写。
          lower-case-service-id: true #是否启动服务名小写
      routes:
        - id: service-business #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
          uri: lb://service-business       #匹配后提供服务的路由地址
          predicates:
            - Path=/business/** # 断言，路径相匹配的进行路由
        - id: service-user #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
          uri: lb://service-user        #匹配后提供服务的路由地址
          predicates:
            - Path=/user/**         # 断言，路径相匹配的进行路由
        - id: service-order #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
          uri: lb://service-order        #匹配后提供服务的路由地址
          predicates:
            - Path=/order/**         # 断言，路径相匹配的进行路由
        - id: service-message #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
          uri: lb://service-message        #匹配后提供服务的路由地址
          predicates:
            - Path=/message/**         # 断言，路径相匹配的进行路由
    nacos:
      discovery:
        server-addr: 8.134.162.31:8848





