server:
  port: 8003
spring:
  application:
    name: service-user
  cloud:
    nacos:
      discovery:
        server-addr: 101.43.171.193:8848
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/elm_user?serverTimezone=GMT%2B8
    username: root
    password: x.z.w.91
  #    jackson日期转换
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  profiles:
    active: dev

    # redis相关配置
  redis:
    host: 101.43.171.193
    port: 6379
    password: asd123
    database: 0
    timeout: 1800000
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
        #最大阻塞等待时间(负数表示没限制)
        max-idle: 5
        min-idle: 0
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml