spring:
  datasource:
    url: jdbc:mysql://8.134.162.31:3306/elm_user?useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: elm
    password: elm
  cloud:
    nacos:
      discovery:
        server-addr: 8.134.162.31:8848

