spring:
  datasource:
    url: jdbc:mysql://8.134.162.31:3306/elm_user?characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: elm
    password: elm
  cloud:
    nacos:
      discovery:
        server-addr: 8.134.162.31:8848
